version: 2
jobs:
  test:
    machine:
      image: circleci/classic:201711-01

    working_directory: ~/cluster-controller

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            # build app
            docker-compose build app

            # because of volumes
            # vendor packages will be erased on runtime
            docker-compose run app make dependecies

            docker-compose run app make test

workflows:
  version: 2
  ci:
    jobs:
      - test